function annotation_on_axes(ax, txt)
text(ax, 0.02, 0.02, txt, 'Units','normalized', ...
    'VerticalAlignment','bottom','HorizontalAlignment','left', ...
    'FontSize',8, 'Interpreter','none');
end
